apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cosmic-backend.fullname" . }}
  labels:
    {{- include "cosmic-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cosmic-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cosmic-backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: PORT
              value: {{ .Values.service.targetPort | quote }}
            - name: APP_ENV
              value: {{ .Values.env | quote }}
            - name: APP_VERSION
              value: {{ .Values.image.tag | quote }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
