apiVersion: v1
kind: Service
metadata:
  name: {{ include "cosmic-backend.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "cosmic-backend.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "cosmic-backend.selectorLabels" . | nindent 4 }}
